name: Build plugin

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Make Gradle wrapper executable
      run: chmod +x ./gradlew

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build

    - name: Upload WorldGuard Bukkit artifact
      uses: actions/upload-artifact@v3
      with:
        name: WorldGuard-Bukkit
        path: worldguard-bukkit/build/libs/worldguard-bukkit-*-dist.jar

    - name: Upload WorldGuard Core artifact
      uses: actions/upload-artifact@v3
      with:
        name: WorldGuard-Core
        path: worldguard-core/build/libs/worldguard-core-*.jar
